name: Testing, Build & Deploy
on:
  workflow_dispatch:
    # branches:
    #   - Testing-manual-deploy

jobs:
  test:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/actions-checkout@v3
