name: Testing, Build & Deploy
on:
  workflow_dispatch:
    # branches:
    #   - Testing-manual-deploy

jobs:
  test:



    steps:
      - name: Checkout code
        uses: actions/actions-checkout@v3
