
name: Testing, Build & Deploy

on:
  push:
  workflow_dispatch:

        inputs:
          force-deploy:
            type: string
            required: true
            # default: false



      

jobs:
  test:

    if:  github.ref == 'refs/heads/develop' ||  github.event.inputs.force-deploy == 'true'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
