name: Testing, Build & Deploy
on:
  push:
  workflow_dispatch:
    # branches:
    #   - Testing-manual-deploy

jobs:
  test:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout code
        uses: actions/checkout@v4
