name: Testing, Build & Deploy
on:
  push:
  workflow_dispatch:

        # inputs:
        #   force-deploy:
        #     type: string
        #     required: true



      

jobs:
  test:

    if:  github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/IRN')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
